os:
  - linux
language: perl
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.10"
  - "5.8.9"
install:
# Deal with dependencies
- cpanm --notest --installdeps .
script:
- perl Makefile.PL
- make
- make test
